import Link from "next/link";
const products=[
["Group Scout","/logos/groupscout.svg","AI-powered community discovery that turns the right conversations into customers."],
["Meeting Sync","/logos/meetingsync.svg","Meetings that capture decisions, surface next steps, and keep teams aligned."],
["Polyscribe","/logos/polyscribe.svg","Turn one great idea into polished, on-brand content for every channel."],
["GroupZen","/logos/groupzen.svg","Intelligent tools that keep growing communities organized, engaged, and healthy."]];
const services=[["01","AI product strategy","Find the highest-leverage AI opportunity, validate it fast, and build the right roadmap."],["02","Custom AI development","Production-grade agents, automations, and applications engineered around your business."],["03","Product engineering","From first prototype to scalable platform, one senior team owns the entire journey."]];
export default function Home(){return <main><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({"@context":"https://schema.org","@type":"ProfessionalService",name:"Appstackers",url:"https://appstackers.com",areaServed:"Worldwide",serviceType:["AI Development","Software Development","AI Product Strategy"]})}}/>
<nav className="nav shell"><Link href="/" className="brand"><img src="/logos/appstackers.svg" alt="Appstackers" width="190" height="42"/></Link><div className="navlinks"><a href="#products">Products</a><a href="#services">Capabilities</a><a href="#process">Process</a></div><a className="button small" href="mailto:hello@appstackers.io?subject=AI project">Start a project ↗</a></nav>
<section className="hero shell"><p className="eyebrow reveal"><i/> AI, built for the real world</p><h1 className="reveal d1">We don’t chase<br/>the future. <em>We ship it.</em></h1><p className="lead reveal d2">Appstackers turns ambitious ideas into AI products people actually use. Strategy, design, and engineering—from a team that builds its own successful software.</p><div className="actions reveal d3"><a className="button" href="mailto:hello@appstackers.io?subject=Let's build with AI">Build your AI advantage ↗</a><a href="#products">See what we’ve built ↓</a></div><div className="visual" aria-hidden="true"><div className="orbit"/><div className="orbit inner"/><b>AI<small>01</small></b><span>STRATEGY · SHIP · SCALE</span></div><div className="proof">STRATEGY <i/> DESIGN <i/> ENGINEERING <i/> GROWTH</div></section>
<section className="section shell" id="products"><header><div><p className="kicker">Our products</p><h2>We build for clients.<br/>We build for ourselves.</h2></div><p>Our products prove the standard we bring to every partnership: useful AI, thoughtful experiences, and software built to scale.</p></header><div className="grid">{products.map((p,i)=><article className="card" key={p[0]}><div className="meta"><span>0{i+1}</span><span>Live product</span></div><div className="plogo"><img src={p[1]} alt={p[0]+" logo"} loading="lazy"/></div><p>{p[2]}</p><a href="https://app.appstackers.io" target="_blank" rel="noreferrer">Explore product <span>↗</span></a></article>)}<article className="card soon"><div className="meta"><span>05+</span><span>In the lab</span></div><strong>More useful<br/>things, coming soon.</strong><p>The next Appstackers product is already taking shape.</p></article></div></section>
<section className="dark section" id="services"><div className="shell"><p className="kicker muted">What we do</p><header><h2>From “what if?”<br/>to <em>what’s next.</em></h2><p>Sharp product thinking meets deep technical execution. No bloated handoffs. No innovation theater. Just a focused senior team shipping measurable value.</p></header><div className="service-list">{services.map(s=><div className="service" key={s[0]}><span>{s[0]}</span><h3>{s[1]}</h3><p>{s[2]}</p><b>↗</b></div>)}</div></div></section>
<section className="section shell" id="process"><header><div><p className="kicker">How we work</p><h2>Momentum by design.</h2></div><p>You’ll always know what we’re building, why it matters, and what comes next.</p></header><div className="steps"><div><span>01</span><h3>Find the edge</h3><p>Align on the opportunity, user, and outcome that matters.</p></div><div><span>02</span><h3>Make it real</h3><p>Prototype quickly and turn signal into a focused build.</p></div><div><span>03</span><h3>Ship & sharpen</h3><p>Launch, learn from real usage, and improve what moves the needle.</p></div></div></section>
<section className="cta shell"><p className="kicker muted">Your unfair advantage starts here</p><h2>Ready to build something<br/><em>people can’t ignore?</em></h2><p>Bring the ambition. We’ll bring the product instinct, AI expertise, and engineering muscle.</p><a className="button light" href="mailto:hello@appstackers.io?subject=Let's build something">Let’s make it happen ↗</a></section>
<footer><div className="shell foot"><div><img src="/logos/appstackers.svg" alt="Appstackers" width="170" height="38"/><p>AI products, built to matter.</p></div><div><b>EXPLORE</b><a href="#products">Products</a><a href="#services">Capabilities</a><a href="#process">Process</a></div><div><b>CONNECT</b><a href="mailto:hello@appstackers.io">hello@appstackers.io</a><a href="https://app.appstackers.io">Product platform ↗</a></div></div><div className="shell bottom"><p>© {new Date().getFullYear()} Appstackers.</p><div><Link href="/privacy-policy">Privacy Policy</Link><Link href="/terms-of-service">Terms of Service</Link></div></div></footer></main>}
